export const metadata = {
  title: 'PillarBank',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <link rel="icon" href="/image/logo.png" sizes="any" />
      <meta name="PillarBank" lang="es" content="Banco"></meta>
      <body>{children}</body>
    </html>
  )
}
